"""initial_tables

Revision ID: e8fafdf17f30
Revises: 
Create Date: 2026-02-16 12:42:38.404091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8fafdf17f30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tts_creator_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('avg_views', sa.Integer(), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('past_products', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.Enum('FASTMOSS', 'TTS_API', name='creatorsource'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tts_creator_id')
    )
    op.create_table('trend_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('sold_count', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('competition_score', sa.Float(), nullable=True),
    sa.Column('top_video_url', sa.String(length=2048), nullable=True),
    sa.Column('video_script', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('FASTMOSS', 'TTS_API', name='datasource'), nullable=True),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.Enum('FREE', 'STARTER', 'PRO', 'ENTERPRISE', name='plantype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('knowledge_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('HOOK', 'SCRIPT', 'TREND', 'STRATEGY', 'PRODUCT', name='knowledgecategory'), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('pinecone_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pinecone_id')
    )
    op.create_table('shops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('shop_name', sa.String(length=255), nullable=False),
    sa.Column('tts_shop_id', sa.String(length=255), nullable=True),
    sa.Column('access_token_enc', sa.String(length=1024), nullable=True),
    sa.Column('refresh_token_enc', sa.String(length=1024), nullable=True),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tts_shop_id')
    )
    op.create_table('cr_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('product_url', sa.String(length=2048), nullable=True),
    sa.Column('purpose', sa.Enum('SALES', 'AWARENESS', 'REVIEW', name='projectpurpose'), nullable=True),
    sa.Column('duration', sa.Enum('SHORT_15S', 'MEDIUM_30S', 'LONG_60S', name='projectduration'), nullable=True),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('reference_videos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('additional_instructions', sa.Text(), nullable=True),
    sa.Column('ai_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATING', 'GENERATED', 'FILMING', 'PUBLISHED', name='projectstatus'), nullable=False),
    sa.Column('performance_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cr_projects')
    op.drop_table('shops')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('trend_products')
    op.drop_table('creators')
    # ### end Alembic commands ###
